### ISSUE TITLE
EOFError when loading "vtskarbonite.mu" from Karbonite mod

### ISSUE THREAD

**Issue by rspeed** [taniwha/io_object_mu#10]
The method `read_float` in `io_object_mu.mu.Mu` raises an `EOFError` when importing "vtskarbonite.mu" from the Karbonite mod. It wasn't providing any useful debugging info, so I modified the code a bit (since I have no idea how to attach a debugger to Blender):

```
raise EOFError("File: {}, Position: {}, Size: {}, Length: {}".format(self.file.name, self.file.tell(), size, len(data)))
```

Which gave this result:

```
EOFError: File: /Users/rspeed/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/GameData/UmbraSpaceIndustries/Karbonite/Assets/vtskarbonite.mu, Position: 255849, Size: 8, Length: 5
```

The file is 255849 bytes in length, so indeed it is trying to read past the end of the file. Just for fun I used a hex editor to throw three more 0x00 bytes on the end of the file, but all that did was make `Mu.read_int` attempt to read ever further past EOF. I don't understand the mu format at all, so there isn't any more info I can provide at the moment.

**Comment by taniwha** [comment]
Seems to have been fixed by 2621dc2e6503f584de6c99acfe5bd5f77da02420
