### ISSUE TITLE
Hard coded path in import_craft.py

### ISSUE THREAD

**Issue by nbgibson** [taniwha/io_object_mu#11]
Starting at line 33 of import_craft.py

```
model_by_path = {}
loaded_models = {}
parts = {}
resources = {}
gamedata = "/home/bill/ksp/KSP_linux-ckan/GameData"
loaded_models_object = None
parts_object = None
```

This causes blender to throw a fit if not fooled around with as the path does not exist in most systems. Please advise.

**Comment by taniwha** [comment]
Set to somewhere appropriate, but yeah, I need to do something about it.

**Comment by Vuzin** [comment]
@taniwha I've changed the path in import_craft.py to my GameData folder but it gives me an error in blender when I try to enable the addon.
![capture](https://user-images.githubusercontent.com/33767291/34886825-a048b28e-f781-11e7-9778-92fd2225e1c1.PNG)
![image](https://user-images.githubusercontent.com/33767291/34886919-e7b48076-f781-11e7-8fb5-dd7816dfaf50.png)

**Comment by taniwha** [comment]
I don't know about the exception you got, but the hard-coding is fixed: the path is specifiable in the addon's panel in user preferences. For that, closing. If the exception persists, please raise another issue.
