### ISSUE TITLE
Can't find .mu files

### ISSUE THREAD

**Issue by Seb-Bianchi** [taniwha/io_object_mu#13]
I tried the add-on with KSP blender to import a full ship, but i dont know why, there's an error saying that no mu files are found. Do you have a tutorial on how to import ships ?

**Comment by taniwha** [comment]
You need to set the GameData path in io_object_mu's panel in User Preferences->Addons.

**Comment by Seb-Bianchi** [comment]
That's what i did, but i still get this error message (image linked). What can i do ?
![capture](https://user-images.githubusercontent.com/31625056/38432479-d8d1723e-39c7-11e8-912f-36988a735808.PNG)

**Comment by Antig-Ivanoff** [comment]
Hello! I'm new here and I don't know anything about this 3D models. Just trying to follow the tutorials aaaand... I faced the same problem. I got Blender 2.79, two addons (kspblender and 'mu' one with all paths written). So I can only import mu-models. But importing *.craft files giving this 'io_object_mu" not found. Ady suggestions?

**Comment by taniwha** [comment]
Ah, I see the problem. rename the directory from io_object_mu-master to io_object_mu. I'll see if I can work out how to determine the name dynamically.

**Comment by Antig-Ivanoff** [comment]
I have renamed this folder in Blender's addons but it still doesn't work. Or I should reinstall it again with new name?

**Comment by taniwha** [comment]
Try a re-install, I guess.
