### ISSUE TITLE
Problem Installing the Addon

### ISSUE THREAD

**Issue by Telekmac** [taniwha/io_object_mu#19]
When trying to install the 2.79 or 2.8 versions of the addon it says it installs and when I check the actual file in file explorer the folder is there but inside of blender it does not show up. There is no way top activate the addon therefore making it useless. Please help

**Comment by HaullyGames** [comment]
Works fine for me.

I had issues before, but was related to download a wrong version.
Make sure you are picking the right branch before click on download.

**Comment by HaullyGames** [comment]
The only issue that I have is more related to texture, sometimes the texture is not on right place.

**Comment by Telekmac** [comment]
Yep i tried all the downloads but nothing prevailed

**Comment by taniwha** [comment]
make sure the directory name does not contain any periods(.): blender cannot import modules that have periods in their names because python cannot (due to how the language works).

**Comment by Telekmac** [comment]
Do you mean in the 2.79 Addon folder. Or inside the mod folder?

**Comment by taniwha** [comment]
inside the addon directory. eg, `io_object_mu-blender2.79` will not work, but `io_object_mu-blender279` (or better, just `io_object_mu`) will work. Thus, just rename the directory after extracting the zip.

**Comment by Telekmac** [comment]
Worked Thanks!
