### ISSUE TITLE
Some issues with uploading to Sketchfab

### ISSUE THREAD

**Issue by bartv42** [taniwha/io_object_mu#3]
Heya,

I do community management work for Sketchfab and I found there are some issues with uploading .blend files that have imported .mu files to Sketchfab. I talked to our developers and it seemed that your importer is assigning a color texture to the normal channel. Could you reach out to me on bart@sketchfab.com so we can help you investigate this further?

Thanks!

Bart

**Comment by taniwha** [comment]
Closing due to age and also I'm pretty sure this is fixed (normals now working properly)
