### ISSUE TITLE
colliders not receiving mu collider data

### ISSUE THREAD

**Issue by Rodg88** [taniwha/io_object_mu#36]
broken here: https://github.com/taniwha/io_object_mu/commit/a7f456759f7f2c34e40e30afe0ea79abc050cff8

working in previous commit version (359c986350d72bc200e5d191c5fd90fa6c5d0478)

**Comment by Rodg88** [comment]
In the broken version, a newly added primitive collider doesn't receive the Mu Collider data in Object Properties

**Comment by taniwha** [comment]
Fixed by 98416ae06cd45a6c7a0180892b0c31233c55112b
