### ISSUE TITLE
Unwrapped textures are not being exported with .mu file

### ISSUE THREAD

**Issue by AlexanderhippoR** [taniwha/io_object_mu#39]
This may be a user error, but I can't seem to export the textures for my .mu file. The part in KSP is clear, but has attachment nodes. I believe the issue is the .mu file does not link to any texture.png.

A hexdump from a mod part shows the name of the unwrapped texture:

```
|<=.........textu|
|re.png....|
```

_This does not exist in my exported part._

Here is a screenshot of the clear part:

<img width="619" alt="Screen Shot 2020-07-25 at 10 53 22 PM" src="https://user-images.githubusercontent.com/64050223/88472628-d07fb480-cec9-11ea-8717-088bac9d5c62.png">

**Comment by taniwha** [comment]
The texture data is never in the .mu file. You have to export the texture yourself and copy to the same place as the .mu file when it is loaded.

Note, however, that if you use the mass-export.py script, any used images will be exported along with your models (but as separate files).
