### ISSUE TITLE
Error when exporting .Mu.

### ISSUE THREAD

**Issue by Camelhairs06** [taniwha/io_object_mu#49]
![image](https://user-images.githubusercontent.com/72108057/108630410-a5a80f80-745c-11eb-8aa6-dd5de9eca769.png)

I get this error message in Blender when I try to export as a .mu. I have tried running Blender as Admin and this didn't help.
Thanks for any help!

**Comment by Camelhairs06** [comment]
I'm closing because it was just me being dumb and forgetting an _ in a part name.

**Comment by Olympic1** [comment]
This is related to #50

**Comment by taniwha** [comment]
You have a mesh with no vertices. Don't do that.
