### ISSUE TITLE
It doesn't import .craft and .mu neither

### ISSUE THREAD

**Issue by Pandolfosigismondo** [taniwha/io_object_mu#51]
I work with the version 2.93.1 of Blender (native no steam) and 1.12.1.3142 of KSP (steam version).

I follow the installation's instructions and how it's [here](https://forum.kerbalspaceprogram.com/index.php?/topic/40056-12-17-blender-283-mu-importexport-addon/) written, however I can't import anything. It display:

![craft file import](https://user-images.githubusercontent.com/73948087/125968786-88bbd7dc-aece-45ff-9bc0-6329646b2ba2.png)
for craft file import.

![mu file import](https://user-images.githubusercontent.com/73948087/125969259-b92b28b5-ce9a-489e-8daa-baf915d029f5.jpg)
for mu file import.

I already tried to look around but I didn't find anything.

I'd be awfully glad if someone could help me.

**Comment by Olympic1** [comment]
This is related to #50

**Comment by Pandolfosigismondo** [comment]
Now I have problem only with the craft one:

![craft file import error traceback](https://user-images.githubusercontent.com/73948087/126033660-5175013a-d52c-46ee-8b8d-68c02d047c2a.png)
