### ISSUE TITLE
is exporting only one object

### ISSUE THREAD

**Issue by cassio165** [taniwha/io_object_mu#52]
everything is correct but it cannot export more than 1 object at a time

**Comment by StoneBlue** [comment]
IIRC, you have to select/highlight *every* object in the tree, in the Outliner

**Comment by taniwha** [comment]
If you mean actually one object, that should not be the case, it should be exporting everything in the tree.
If you mean just the one module: take a look at mass-export.py.

**Comment by taniwha** [comment]
> IIRC, you have to select/highlight every object in the tree, in the Outliner

No, just the root object.

**Comment by taniwha** [comment]
Seems to be expectations.
