### ISSUE TITLE
Error trying import .mu in 2.83

### ISSUE THREAD

**Issue by DSymfunny** [taniwha/io_object_mu#56]
[Mu] Unrecognized format: magic 4e454c42 version 760366404
[Mu] Unrecognized format: magic 4e454c42 version 760366404

Trying import .mu apear that

**Comment by taniwha** [comment]
4e454c42 is little-endian "BLEN", It looks like you're trying to import a blender file.
First 16 bytes of a random blender file:

    00000000  42 4c 45 4e 44 45 52 2d  76 33 30 32 52 45 4e 44  |BLENDER-v302REND|
