### ISSUE TITLE
Anywayes to use this add on in blender 3.0 ???

### ISSUE THREAD

**Issue by SkyDraco-8bit** [taniwha/io_object_mu#58]
I tried importing crafts and this happens 
![image](https://user-images.githubusercontent.com/80839516/152245690-4f1e5f9e-c9eb-400e-b579-483076ad728a.png)

any help ? i know i should use blender 2.8 for this but it's loong to reverse to older versions, and i know i am only going to use it for my KSP animations

**Comment by marianstoica2** [comment]
You can install multiple versions of Blender alongside without them interfering, they will each have their own Preferences and Scripts folder, on Windows, there will be a folder for each version.
I have Blender 1.83 and 3.0 installed, you import and export the .mu to .blend in 1.83 (or any other version that works) and open it in 3.0

**Comment by taniwha** [comment]
This can be considered fixed from b4cd4372047ed3510135172195f0abbf6b1072ab (actually earlier, but that broke 2.83 support).
