### ISSUE TITLE
Mu import issue.

### ISSUE THREAD

**Issue by Avalon304** [taniwha/io_object_mu#6]
Errors out when importing a part. Part in question is part of the KSOS pack. The Super 25 Command module and cargo bay.

![error](https://cloud.githubusercontent.com/assets/8188470/6456269/dca312fc-c114-11e4-9e91-212901e1008f.png)

**Comment by taniwha** [comment]
Seems to be fixed by 2621dc2e6503f584de6c99acfe5bd5f77da02420
