### ISSUE TITLE
Parts resized by Tweakscale in KSP revert back to their default size when imported into Blender

### ISSUE THREAD

**Issue by Elevatorisbest** [taniwha/io_object_mu#66]
Newest KSP version, newest Blender version with my aircraft being mostly vanilla (with exception of few BDynamics parts).

I have the wings on my plane scaled down (and up in one spot) with Tweakscale in-game, and they look great, but when imported into blender, they revert back to their default scale which looks more or less out of place (depending on the design of your saved craft).

I will provide the .blend file as well as the .craft file tommorow when I will have access to my PC.

**Comment by taniwha** [comment]
The craft importer does not (and cannot) understand every part module out there, so it understand none. For what you want, you will need to make the instances real (select relevant object (imported craft), ctrl-A, "Make Instances Real", then scale the appropriate parts yourself. You may need to do the conversion step several times.
