### ISSUE TITLE
Normals incorrect after export

### ISSUE THREAD

**Issue by zlsa** [taniwha/io_object_mu#7]
When exporting a model, the normals appear to be wrong in KSP but not in Blender. (You have to look in the VAB because I used the diffuse shader and for some reason it ignores normals... or something. It's obvious in the VAB but not in flight.)

https://drive.google.com/file/d/0B3KjWA5ZuxhrcU1USzRSVWgwRnM/view?usp=sharing

Blender version 2.75 and latest git, KSP 1.0.4, io_object_mu latest version from this repository.

![2015-08-31-165753_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6366062/9593303/855907a0-5001-11e5-914c-65b478a8752c.png)

**Comment by nevercast** [comment]
Perhaps the vectors are not corrected, per this post: https://forum.kerbalspaceprogram.com/index.php?/topic/169530-blender-to-unity-to-ksp-orientation/&tab=comments#comment-3267258

Obviously the vertices are accounted for, could the normals be ignored?

**Comment by taniwha** [comment]
not sure this is still relevant. If it is, please open a new bug
